config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :kittens
  root 'kittens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.invalid?
      redirect_to new_kitten_path
      flash.alert = "Try again"
    else
      @kitten.save
      redirect_to kitten_path(@kitten.id)
      flash.alert = "Kitten created"
    end
  end

  def edit
    @kitten = Kitten.find_by(params[:id])
    
    flash.alert = "Kitten Updated"

  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      redirect_to(@kitten)
    else
      render 'new'
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    flash[:notice] = 'Kitten removed'
    redirect_to root_path

  end

  private

  def kitten_params
    params.require(:kitten).permit( :name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten, local:true do |f| %>
  <%= f.label :name %>
    <%= f.text_field :name %><br>
  <%= f.label :age %>
    <%= f.number_field :age %><br>
  <%= f.label :cuteness %>
    <%= f.number_field :cuteness %><br>
  <%= f.label :softness %>
    <%= f.number_field :softness %><br>
  <%= submit_tag("submit") %>
<% end %>

app/views/kittens/edit.html.erb
<h2>Update</h2>

<%= render 'form' %>

<%= link_to 'Delete', kitten_path(@kitten), method: :delete, data: {confirm: 'Are you sure you want to delete?'}%><br>
<%= link_to 'Back', root_path %>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>

<% flash.each do |type, msg| %>
  <%= msg %>
<% end %>

 <table>
   <tr>
     <th>Name</th>
     <th>Age</th>
     <th>Cuteness</th>
     <th>Softness</th>
   <tr>

    <% @kittens.each do |kitten| %>
      <tr>
        <td><%= link_to kitten.name, edit_kitten_path(kitten.id)%></td>
        <td><%= kitten.age %></td>
        <td><%= kitten.cuteness %></td>
        <td><%= kitten.softness %></td>
        <td><%= link_to 'Delete', kitten_path(kitten.id), method: :delete, data: {confirm: 'Are you sure you want to delete?'}%></td>
      </tr>
    <% end %>
  </table><br>
<%= link_to 'New', new_kitten_path %>

app/views/kittens/new.html.erb
<h1>Create</h1>
<% flash.each do |type, msg| %>
  <%= msg %>
<% end %>

<%= render 'form'%>

<%= link_to 'Back', root_path %>

app/views/kittens/show.html.erb
<h1> Details</h1>

<% flash.each do |type, msg| %>
  <%= msg %>
<% end %>

 <table>
   <tr>
     <th>Name</th>
     <th>Age</th>
     <th>Cuteness</th>
     <th>Softness</th>
   <tr>
   
   <tr>
     <td><%= @kitten.name %></td>
      <td><%= @kitten.age %></td>
      <td><%= @kitten.cuteness %></td>
      <td><%= @kitten.softness %></td>
    </tr>
  </table><br>
<%= link_to 'New', new_kitten_path %><br>
<%= link_to 'Home', root_path %><br>
<%= link_to 'Delete', @kitten, method: :delete, data: {confirm: 'Are you sure you want to delete?'}%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApiDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>